// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAupqhIojooOkp-kQ6e5lyGxavLl2i6luQ',
    appId: '1:451594729231:web:2558e71eca768df151707a',
    messagingSenderId: '451594729231',
    projectId: 'mycattlemonitor',
    authDomain: 'mycattlemonitor.firebaseapp.com',
    storageBucket: 'mycattlemonitor.firebasestorage.app',
    measurementId: 'G-5K2PSECC3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9TJxi7qSd7Gc9WaV4pOKp3ivI__fJtY0',
    appId: '1:451594729231:android:ef678d62ebe847b451707a',
    messagingSenderId: '451594729231',
    projectId: 'mycattlemonitor',
    storageBucket: 'mycattlemonitor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgBJp8VpByy9llZvpGQmVQ_VDqp0MeAoI',
    appId: '1:451594729231:ios:755cb7cd07765f1b51707a',
    messagingSenderId: '451594729231',
    projectId: 'mycattlemonitor',
    storageBucket: 'mycattlemonitor.firebasestorage.app',
    iosBundleId: 'com.example.mycowmanager',
  );

}